# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class LoginObject(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(573, 464)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.leftImage = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftImage.sizePolicy().hasHeightForWidth())
        self.leftImage.setSizePolicy(sizePolicy)
        self.leftImage.setStyleSheet("#leftImage{\n"
"    background-color: aqua;\n"
"}")
        self.leftImage.setObjectName("leftImage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftImage)
        self.verticalLayout_3.setContentsMargins(0, 0, 6, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(parent=self.leftImage)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(80)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout.addWidget(self.leftImage, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 6, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.signUpLBL = QtWidgets.QLabel(parent=self.widget)
        self.signUpLBL.setMaximumSize(QtCore.QSize(16521959, 12591295))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.signUpLBL.setFont(font)
        self.signUpLBL.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.signUpLBL.setStyleSheet("#signUpLBL:hover{\n"
"    color: blue;\n"
"}")
        self.signUpLBL.setObjectName("signUpLBL")
        self.verticalLayout_2.addWidget(self.signUpLBL, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.usernameLE = QtWidgets.QLineEdit(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameLE.sizePolicy().hasHeightForWidth())
        self.usernameLE.setSizePolicy(sizePolicy)
        self.usernameLE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setKerning(True)
        self.usernameLE.setFont(font)
        self.usernameLE.setAcceptDrops(True)
        self.usernameLE.setAutoFillBackground(False)
        self.usernameLE.setStyleSheet("#usernameLE{\n"
"    border-radius: 12px;\n"
"    background-color: rgba(123,123,123, 0.4)\n"
"}\n"
"\n"
"#usernameLE:hover{\n"
"    background-color: rgba(123,123,123,0.7)\n"
"}")
        self.usernameLE.setMaxLength(50)
        self.usernameLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.usernameLE.setObjectName("usernameLE")
        self.verticalLayout_2.addWidget(self.usernameLE)
        self.passwordLE = QtWidgets.QLineEdit(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLE.sizePolicy().hasHeightForWidth())
        self.passwordLE.setSizePolicy(sizePolicy)
        self.passwordLE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.passwordLE.setFont(font)
        self.passwordLE.setStyleSheet("#passwordLE{\n"
"    border-radius: 12px;\n"
"    background-color: rgba(123,123,123,0.4)\n"
"}\n"
"\n"
"#passwordLE:hover{\n"
"    background-color: rgba(123,123,123,0.7)\n"
"}")
        self.passwordLE.setMaxLength(50)
        self.passwordLE.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.passwordLE.setObjectName("passwordLE")
        self.verticalLayout_2.addWidget(self.passwordLE)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.loginButton = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginButton.sizePolicy().hasHeightForWidth())
        self.loginButton.setSizePolicy(sizePolicy)
        self.loginButton.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.loginButton.setFont(font)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.loginButton.setStyleSheet("#loginButton{\n"
"    border: 0;\n"
"    border-radius: 12px;\n"
"    background-color: rgba(111,111,111, 0.6)\n"
"}\n"
"\n"
"#loginButton:hover{\n"
"    background-color: rgba(111,111,111, 1)\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout_2.addWidget(self.loginButton)
        spacerItem6 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 10)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.loginWarningLBL = QtWidgets.QLabel(parent=self.widget)
        self.loginWarningLBL.setText("")
        self.loginWarningLBL.setObjectName("loginWarningLBL")
        self.verticalLayout_2.addWidget(self.loginWarningLBL)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(6, 3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(Form)
        self.passwordLE.returnPressed.connect(self.loginButton.click) # type: ignore
        self.usernameLE.returnPressed.connect(self.loginButton.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Login"))
        self.signUpLBL.setText(_translate("Form", "Create a new account"))
        self.usernameLE.setPlaceholderText(_translate("Form", "Username / Email"))
        self.passwordLE.setPlaceholderText(_translate("Form", "Password"))
        self.loginButton.setText(_translate("Form", "Sign in"))
