# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class RegisterObject(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(573, 464)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.leftImage = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftImage.sizePolicy().hasHeightForWidth())
        self.leftImage.setSizePolicy(sizePolicy)
        self.leftImage.setStyleSheet("#leftImage{\n"
"    background-color: aqua;\n"
"}")
        self.leftImage.setObjectName("leftImage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftImage)
        self.verticalLayout_3.setContentsMargins(0, 0, 6, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(parent=self.leftImage)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(80)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout.addWidget(self.leftImage, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 6, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.signInLBL = QtWidgets.QLabel(parent=self.widget)
        self.signInLBL.setMaximumSize(QtCore.QSize(16521959, 12591295))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.signInLBL.setFont(font)
        self.signInLBL.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.signInLBL.setStyleSheet("#signUpLBL:hover{\n"
"    color: blue;\n"
"}")
        self.signInLBL.setObjectName("signInLBL")
        self.verticalLayout_2.addWidget(self.signInLBL, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.emailLE = QtWidgets.QLineEdit(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailLE.sizePolicy().hasHeightForWidth())
        self.emailLE.setSizePolicy(sizePolicy)
        self.emailLE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setKerning(True)
        self.emailLE.setFont(font)
        self.emailLE.setAcceptDrops(True)
        self.emailLE.setAutoFillBackground(False)
        self.emailLE.setStyleSheet("#emailLE{\n"
"    border-radius: 12px;\n"
"    background-color: rgba(123,123,123, 0.4)\n"
"}\n"
"\n"
"#emailLE:hover{\n"
"    background-color: rgba(123,123,123,0.7)\n"
"}")
        self.emailLE.setMaxLength(50)
        self.emailLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.emailLE.setObjectName("emailLE")
        self.verticalLayout_2.addWidget(self.emailLE)
        self.usernameLE = QtWidgets.QLineEdit(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameLE.sizePolicy().hasHeightForWidth())
        self.usernameLE.setSizePolicy(sizePolicy)
        self.usernameLE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setKerning(True)
        self.usernameLE.setFont(font)
        self.usernameLE.setAcceptDrops(True)
        self.usernameLE.setAutoFillBackground(False)
        self.usernameLE.setStyleSheet("#usernameLE{\n"
"    border-radius: 12px;\n"
"    background-color: rgba(123,123,123, 0.4)\n"
"}\n"
"\n"
"#usernameLE:hover{\n"
"    background-color: rgba(123,123,123,0.7)\n"
"}")
        self.usernameLE.setMaxLength(50)
        self.usernameLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.usernameLE.setObjectName("usernameLE")
        self.verticalLayout_2.addWidget(self.usernameLE)
        self.passwordLE = QtWidgets.QLineEdit(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLE.sizePolicy().hasHeightForWidth())
        self.passwordLE.setSizePolicy(sizePolicy)
        self.passwordLE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.passwordLE.setFont(font)
        self.passwordLE.setStyleSheet("#passwordLE{\n"
"    border-radius: 12px;\n"
"    background-color: rgba(123,123,123,0.4)\n"
"}\n"
"\n"
"#passwordLE:hover{\n"
"    background-color: rgba(123,123,123,0.7)\n"
"}")
        self.passwordLE.setMaxLength(50)
        self.passwordLE.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.passwordLE.setObjectName("passwordLE")
        self.verticalLayout_2.addWidget(self.passwordLE)
        self.passwordLE_2 = QtWidgets.QLineEdit(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLE_2.sizePolicy().hasHeightForWidth())
        self.passwordLE_2.setSizePolicy(sizePolicy)
        self.passwordLE_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.passwordLE_2.setFont(font)
        self.passwordLE_2.setStyleSheet("#passwordLE_2{\n"
"    border-radius: 12px;\n"
"    background-color: rgba(123,123,123,0.4)\n"
"}\n"
"\n"
"#passwordLE_2:hover{\n"
"    background-color: rgba(123,123,123,0.7)\n"
"}")
        self.passwordLE_2.setMaxLength(50)
        self.passwordLE_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLE_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.passwordLE_2.setObjectName("passwordLE_2")
        self.verticalLayout_2.addWidget(self.passwordLE_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.registerButton = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerButton.sizePolicy().hasHeightForWidth())
        self.registerButton.setSizePolicy(sizePolicy)
        self.registerButton.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.registerButton.setFont(font)
        self.registerButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.registerButton.setStyleSheet("#registerButton{\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    background-color: rgba(111,111,111, 0.6)\n"
"}\n"
"\n"
"#registerButton:hover{\n"
"    background-color: rgba(111,111,111, 1)\n"
"}")
        self.registerButton.setObjectName("registerButton")
        self.horizontalLayout_2.addWidget(self.registerButton)
        spacerItem6 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 10)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.registerWarningLBL = QtWidgets.QLabel(parent=self.widget)
        self.registerWarningLBL.setText("")
        self.registerWarningLBL.setObjectName("registerWarningLBL")
        self.verticalLayout_2.addWidget(self.registerWarningLBL)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.verticalLayout_2.setStretch(8, 3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(Form)
        self.passwordLE.returnPressed.connect(self.registerButton.click) # type: ignore
        self.usernameLE.returnPressed.connect(self.registerButton.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Sign Up"))
        self.signInLBL.setText(_translate("Form", "Already have an account?"))
        self.emailLE.setPlaceholderText(_translate("Form", "Email"))
        self.usernameLE.setPlaceholderText(_translate("Form", "Username"))
        self.passwordLE.setPlaceholderText(_translate("Form", "Password"))
        self.passwordLE_2.setPlaceholderText(_translate("Form", "Password"))
        self.registerButton.setText(_translate("Form", "Sign Up"))
